apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triqui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bicora/triqui-kube-config
    targetRevision: HEAD
    path: manifests/environments/uat/triqui-client
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - createNamespace=true
    automated:
      selfHeal: true
      prune: true
