apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCIvDFBybhBSDJIuZvMLJNZm79xLA/kS+fev7eFkQ81kqiGkYOH5z4mThLx8k4YQsKPbYaUWPMfTw/0Zvp5v7wLHVHY74AcI2HlWdrYhqVC2jtkc4RSPK9jr9zujyFiltws2T6wHCnXzB4rIXIh5+4BbLYs2c/apYvsjHyUmJcN7oikVPV9fOIcQ2eFwN9Fx0ueOfAs/JkTrWKmKFE6dZU++L2PAR4l0/SofgFy4mwQW2qBe0upBGxJqpFb+BZasxCBcLqTvPi1rgkv9uSz/t5yrtcHNNThzoO4j9zkp+SB1lekq6H/9rxM2VO/p87BcVcq+bumDbhFlzpi89p/IgEa0BEfmkeWiR4RM5Sd79QyhxeFs324zDyaN19k3ziKaP2DLpxRS71Tp3HhhT4cGKACLUSavJiRgQIhJcIcUZ5P0aM1I0uOsyIokwYlepmlnUzIyV9UA7IBoaSDlzUjmf0/lBsrRiVf8zcyCY/BH0TS/iYLGsxaYYrQkqh9h5HzujgA7wTtqDpRSUPNHZ0sI35w/0twZJu48tMeUeISwE5f5wVSTgb3Xq0Ha0ylVA3+m5DAIwv9p4+vz/Ga9ZsVdOVWtDpobqIR8diNbON7pEXb1j11zgZ8osgKej2jeFc9UXIFI5ETC8W+3ch/jayJBKJbswMAemjphYxCngSklWIz5FYraWJQNv7pfulqhjpgixWqtur3f/lyzmynIaJyXmukQewrwD6cihQegvZExzGjjahsWQ1/peAB2COWPu55Dm//k1Zu77cU9vv/2reJ3mupzXsmgzR4H8S7Do2Qccr4gdkkPqlYxSLlst6Rc/DJ6lVSU2uwNBkNV8KYSnif84F9JFDkuA/VuECGYrrnpAgh
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

