apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAtNZcKlXCpdYPbe+Z1OVWt15ZQLxN7TlPRo9VosjgQZJkNSsJ5WmK3beZfR8tEsAVsKL4stwm0iC/76b9AWA9iS5RYYPL9hMVUnVZf6M7bufQGzhgwTPvpSMbWkAiuj/UWVnB7gIC8JxNYQIqhRH/BX1FtdK6mrmyYMd/TFcdV15pFQyYObiPRYoBRMCRKWNwl+OfmVraZ+qco6Q+kaCTHS/foz/JO2HgHtIAu+BT4dP9R/n++bM0X/Y7G4TFfaKlm4rFJefkGUH3FvMv8JBdT+7hY+9twwVxvYLMqyty0ASyR6LGdM02l040Q7Ep+ytNnJHOLqbUlCkZJfjH9n7RORno66uC3RK9FsAcCSJiNaU7D12/sfXfCYpzISiF3+DT385MgZIn0QsMP0ANlLJMUCHabcA3NoLADvgb1PbJulle1lMdpZKCqgtXXXV+e3QFALwEiuSaqwlNlj67027jfeI/uJl7OBQSc9386GAkDBGEzdc1d3jKjTXSpARnH4LV6UmZhr7PGQ6AAYesgW0pTud7Fks2WvaTA18jkolG+O2zYl3qGKnQMS3DR4ULv5Ef6EHxS/Gkw5Hg6NsI7I7NoTY6BDMy9llrvNmjYFGVASkEcYqxQOCX51JEBIHBZXU2zxhyoBX3FaclpZVh5/imSs0AWMHMGyC/80bCgXminci8rfKyWCrwtDqAhlhHPGUdYI04kIVvymmMdV2B7OgFFOJURWr2LSO7YhBR1i4oPDEwLJ99fNuS+Zy6qfEnou/XWNh5jad/8ojKredUrKYD6cZgp1SASIVGJl4r/TO0f4b13rpRAdQxSEHUiaGryXsTCvOr2dwjgxFyLMVj2bIAOHW1tbYL7vEpLQhfunm84
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

