apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
spec:
  encryptedData:
    .dockerconfigjson: AgBLmIGGaEl9zbk5mY621TMCW2vYr0Lwrtbd4dYeZQg/aGK1rhYa5m2kyslrPt2Sy0/Mf13nHuyDM10UATuwaJ8HfajcrS14vAEbq9LXKmD8tnf7i/zxJ3TxZQQyFBbtoWLFE26ph9rBBVLLq5cdtyXgUgEvsWUxP7HwAISTGwDk/Xxxkhch76o4OnQZV4mlZLuINYapu0I7W0mcL3WsiBP3OLRwNReRcHiEnjFAy8oqPMLvaPz2F3MSruWLpTgYHBnGuw3Zn+5jWUeYK19wYSkEXNTiGf+jR5OjbDAWwLjBR4VQ4G3XE5ffobltR9f9RPq15mEgfvfndOj+ryabKHSfxVe690fxBeIMsqsgGzfY+/Yp4BZbl2YNubpaX5SSwB3jm0L4kO+hesXxCcaSYGAPhjQ7RT/mloqSEReXdgjkNsDT20Per3KGnxw03opWc09TfTYppRmTKxjL2/hHapf7pIdM+qfp+jfwwoUgJPVqFeo0G06AYxRCSsPcGx37vnurcBqHMXSoC54lVMzeVeNRd7BnWaUGzwatSH2ojQEKqmiv2LIzQgor/dYjhC3oalxrTbRGT1vpFsd+3qLDeoti/aR6JwVFebzWPk3TFdk+r6eohLiordiT82UbYXDLUOp6vYxKQOgTxLIamx8EL7VAeAP4/nI8WxTUdNQ+sxDrDQVLo85fn9NqZUHZTBkv0730Z/2+dPPxcKUkv7T1kvcFrEuTo2yngL7TVNJVwzQ7kEYy+UOY22y+S8DjQdqlDWgOUB3LxrNuNZKpYKcNdKhTCDPTEsz53/vEBS7dHxB2q7+cnbfhEx8YaDXWB921Yt2K8rayQ6rOaQX7esW0WbeZtINF7GNjHZXlHjx2J/TH
  template:
    type: kubernetes.io/dockerconfigjson

