apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBP+HQ/qw6hXhsgDVQ54RNpLOB66g3wGsiApfvUXBQRkLqxkpytpfWFzoP056j7xTc1HxODcmObs7+xChvypTfasQSD87NqMRRBCOfmhxr4/BxWrxXd7mGTCeFgJYq+GuFB4mSaT4gFeRYBLPRRPxA0tJ6g2Yrd73Hi8L6Pi3ckhpImWvWlu6OoYEvn3JGFVT0B7+kxS512E5+PaQZl0SRjfqDkzCn8RumERI3gjLvJbx+jKqP3SIKHSVlImJ4rPhSNY/PoVT/CPd/5mkwTBSvcel0u+C0iJySTHOwO89AuY0XxcHJCGb8+s0clyZX67/Z6LTcuh8E1X4O6KbJC0zuvy6AgH+g4S47ViSsUcduqhokOQpTt4OTquK9m8PdSBg10G2pEsYNT/UBNlCOVPaelM/HngWfaQPXmpyB2oImB1RDY6ZuGOTdFDSLi+8vnezsCtNPXIn9zVjWagh1S3zphqacQSCQuCteIRy7ITFhmNBsWZSIbDdDOpyd2QH55CFonXgcqhtMckKAlhd5pf3S4IAKfWoLBNmR6avFl1vXbXE0g8qydsKLVAcVVjifpCGv3/cRet9SJ2AtOC1klt76G/R5kqtjwguIahTXGdBh81S2521/ngH9EBA4WGcByMdL8IRs+q4WygEAXbLhC04MgrZ39Hbk/ZS+zc2S82Z9NFpCLebGQzdPrHhKYAmXI8+ufXSvTovqXTk+BZm5jOy/5oUfLmjZlCAMIT0jHXbVs0QmJpPoNydSz/dhYYPjPv7443BwNn+l8eTD7RclA8T2gTRp+mwUrq3C3pa9vxrcC+bvfQvlF0UjW3a/K9vDdsHtAaSIBo4tewBKym8PZIJpSEIBzGYdcJr+QcktOBDYR
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

