apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: triqui
spec:
  encryptedData:
    .dockerconfigjson: AgARrbXMfTQg4HE+wlRyJAqBsLX9y+XMdOmep46kJJpmrhtAZWmEGTVK06t/XG0jbiOwy6AKhQXdTU8ZPaVPxS/A/u8vE9BMIHBc/xVGnIKQMnO99mLE115XifB3/Sdmq7PV4G3W90J3nQnNJPBjreCZ+sR8AS8U+wHUNW/J3CutqrBdgEdQRlB6ApYjwszeNu62p9rpiS57l2bmQbgpH9Dq0ABzAaiLGun+4dMK80Y75LrDj/0HhQMpDokShbKytC1tM05WwaO+1L0JK03ml57Ecg5qm+hGPX4BbEAD6bTaSp0UbXUjYUyfCVURC2wHKvg5a6vKyC/pL7l11p+orn/AZ6xEUXkV5ERNy0u+ZxKrPFCTK1ViE/IT309ckHJJjuvY/DJWBseocxX0p8OEQrfvABHzci6MoKGZcmPD3ndtoViTNgv5CNe/vHOmFVDsG9hVmVTN/gyYrBjRZaMFE0F5Gq3HTttOPtIH6sT/vBPOCmME6FZDqfG9keZO6z6kPtl77eKXTHPdy/k3kxvZN/0IBr8Et66IVww/G3UwA4UUPpMBVK2KBnHWD2MJPxMlz5rvDQeiC7/K6racADkPgEZFcqXDMKyNQFTyO85wrl1FWNxg2VPJtKou67Jv9KasV/uZFdSKBOj/T6LrJrmWuJlmYLzMSDMolKv7kMf7dsiMK3d2o6Snhlpjg4sW6tTkdimhaIph2YBDOe7xQ6McCUSoJNPaWqMCNgjC/WVKsBxpw/vAWdUHSYWUrpxb/ccdm1q5VxpHbH2YtxbSgQVoV1kbRuLmNRyfSiBBnnOTf8LqQ39clzwNeQnmPJJHjJMXYFlYMxy0ck+itGNBlZZP9vasVK3nmJuiA6tq5rZ+nhZ0
  template:
    metadata:
      name: ghcr-secret
      namespace: triqui
    type: kubernetes.io/dockerconfigjson

