apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: camimueco27@gmail
    privateKeySecretRef:
      name: triqui-staging
    solvers:
    - http01:
        ingress:
          class:  nginx